### ISSUE TITLE
Wrong wifi password is not recognised

### ISSUE THREAD

**Issue by rdmitry0911** [usr-sse2/Black80211-Catalina#28] opened 2020-08-11 05:23 UTC
On my 9560 if I enter a wrong password while connecting, the system does not recognise it as wrong. It accepts it and after a while it shows the connection as established without internet access and with self-assigned ip address. There is no way to change the password to the right one. I have to delete the corresponding item via keychain access and reboot the system to be able to enter the password again.

**Comment by usr-sse2** [comment] 2020-08-16 13:48
This issue is duplicate of #1. I'm currently working on using Apple RSN supplicant instead of a built-in one, so it will handle it itself (and should also support WPA Enterprise).
There is no need to delete from Keychain Access and reboot – there is an UI for that:
![Снимок экрана 2020-08-16 в 16 43 32](https://user-images.githubusercontent.com/446776/90335815-1ff46480-dfe0-11ea-8fd5-7c5a01a78ac7.png)
![Снимок экрана 2020-08-16 в 16 43 43](https://user-images.githubusercontent.com/446776/90335820-24b91880-dfe0-11ea-8760-9e01bd51d078.png)
Just remove the network from known network list using a '–' button.

**Closed by usr-sse2** 2020-08-16 13:48 UTC
Labels: bug, duplicate

**Comment by rdmitry0911** [comment] 2020-08-17 07:19
> Just remove the network from known network list using a '–' button.

It might be even more difficult if the list contains 200+ network names and there is no search function
